name: RAI
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  percent_indicator: ^1.0.15
  dio: ^2.1.2
  shared_preferences: ^0.5.2
  pigment: ^1.0.3
  carousel_slider: ^1.3.0
  liquid_pull_to_refresh: ^1.1.0
  flutter_slidable: ^0.4.9
  flutter_svg: ^0.12.4
  font_awesome_flutter: ^8.4.0
  local_auth: ^0.4.0+1
  pin_code_view: ^0.2.1
  rxdart: ^0.21.0
  date_format: ^1.0.6
  flutter_masked_text: ^0.8.0
  flutter_money_formatter: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/logo-bc.color.png
    - assets/img/logo-bc.png
    - assets/img/logo-lo.color.png
    - assets/img/logo-lo.png
    - assets/img/logo-scb.color.png
    - assets/img/logo-scb.png
    - assets/svg/savewise-logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family: Savewise
      fonts:
      - asset: assets/fonts/Savewise.ttf
    - family: Gotham
      fonts:
      - asset: assets/fonts/Gotham-Black.otf
        weight: 900
        style: normal
      - asset: assets/fonts/Gotham-Bold.otf
        weight: 800
        style: normal
      - asset: assets/fonts/Gotham-BookItalic.otf
        weight: 500
        style: italic
      - asset: assets/fonts/Gotham-Light.otf
        weight: 300
        style: normal
      - asset: assets/fonts/Gotham-Thin.otf
        weight: 100
        style: normal
      - asset: assets/fonts/Gotham-ThinItalic.otf
        style: italic
        weight: 100
      - asset: assets/fonts/Gotham-UltraItalic.otf
        style: italic
        weight: 900
      - asset: assets/fonts/Gotham-XLight.otf
        weight: 200
        style: normal
      - asset: assets/fonts/Gotham-XLightItalic.otf
        weight: 200
        style: italic
    - family: Proxima
      fonts:
      - asset: assets/fonts/ProximaNova-AltBold.otf
      - asset: assets/fonts/ProximaNova-AltLight.otf
      - asset: assets/fonts/ProximaNova-AltThin.otf
      - asset: assets/fonts/ProximaNova-Black.otf
      - asset: assets/fonts/ProximaNova-Bold.otf
      - asset: assets/fonts/ProximaNova-ExtraBold.otf
      - asset: assets/fonts/ProximaNova-Regular.otf
      - asset: assets/fonts/ProximaNova-Thin.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
