/// Flutter icons Savewise
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Savewise
///      fonts:
///       - asset: fonts/Savewise.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Savewise {
  Savewise._();

  static const _kFontFam = 'Savewise';

  static const IconData arrow_down = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icon_deposit = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData icons8_1_circled_left = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData icons8_1_circled_right = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icons8_appointment_reminders = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData icons8_graph = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icons8_help = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData icons8_minus_sign = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData icons8_pencil = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData icons8_plus = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData icons8_star = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData icons8_team = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData icons8_user_female = const IconData(0xe80e, fontFamily: _kFontFam);
}
